GET http://localhost:5000/feature

###
GET http://localhost:5000/feature/618507d901f78033bf11f1ad

###
POST http://localhost:5000/feature
Content-Type: application/json

{
    "name": "Door"
}

###
DELETE http://localhost:5000/feature/618507d901f78033bf11f1ad

###
PATCH  http://localhost:5000/feature/618507d901f78033bf11f1ad
Content-Type: application/json

{
    "buildId": "DST_H033" 
}
