GET http://localhost:5001/feature

###
GET http://localhost:5001/feature/619e412f5fae31bf70e6c66a

###
GET http://localhost:5001/feature/coverage/619f67a0104fac532794c14a

###
POST http://localhost:5001/feature/61aeea97fb429d7df8a94c6e
Content-Type: application/json

{
    "name": "Door"
}

###
DELETE http://localhost:5001/feature/product/61a46d4608c76d7372c7713e
###
DELETE http://localhost:5001/feature/61adb7c8a5fc1368019091d0
