GET http://localhost:5001/feature

###
GET http://localhost:5001/feature/619e412f5fae31bf70e6c66a

###
GET http://localhost:5001/feature/coverage/619f67a0104fac532794c14a

###
POST http://localhost:5001/feature/619f4cea44686c0bb92a6d14
Content-Type: application/json

{
    "name": "Door"
}

###
DELETE http://localhost:5001/feature/product/619f4cea44686c0bb92a6d14
###
DELETE http://localhost:5001/feature/619f222d4a50b364d25fab50

###
PATCH  http://localhost:5001/feature/619f183bcc7cd74a05cdf97e
Content-Type: application/json

{
    "name": "Door" 
}
