GET http://localhost:5001/product

###
GET http://localhost:5001/product/619f4cea44686c0bb92a6d14

###
POST http://localhost:5001/product
Content-Type: application/json

{
    "name": "ACAMEP",
    "buildId": "DST_H036",
    "listOfFeatures": ["Wall", "Door", "Room"] 
}


###
DELETE http://localhost:5001/product

###
DELETE http://localhost:5001/product/61a46f26a46904fb2704a72c

###
PATCH  http://localhost:5001/product/619f67a0104fac532794c14a
Content-Type: application/json

{
    "buildId": "DST_H040"
}
