GET http://localhost:5001/product

###
GET http://localhost:5001/product/619e41225fae31bf70e6c65c

###
POST http://localhost:5001/product
Content-Type: application/json

{
    "name": "ACAMEP",
    "buildId": "DST_H036",
    "listOfFeatures": ["Wall", "Door", "Room"] 
}

###
DELETE http://localhost:5001/product

###
DELETE http://localhost:5001/product/619e41225fae31bf70e6c65c

###
PATCH  http://localhost:5001/product/619e412f5fae31bf70e6c669
Content-Type: application/json

{
    "buildId": "DST_H039"
}
