GET http://localhost:5001/product

###
GET http://localhost:5001/product/619f4cea44686c0bb92a6d14

###
POST http://localhost:5001/product
Content-Type: application/json

{
    "name": "ACAMEP",
    "buildId": "DST_H036",
    "listOfFeatures": ["Wall", "Door", "Room"] 
}


###
DELETE http://localhost:5001/product

###
DELETE http://localhost:5001/product/61b1bb891f164d8686781d3b

###
PATCH  http://localhost:5001/product/61a733447e57e3d62d9412b5
Content-Type: application/json

{
    "buildId": "DST_H040"
}
