GET http://localhost:5001/testcase

###
GET http://localhost:5001/testcase/feature/619f4d601102c1ca3a1385bc

###
POST http://localhost:5001/testcase/619f9a502957cb7f3d2dccc0
Content-Type: application/json

{
    "data": 
    [{"name": "TestcaseA",
    "description": "Testing API",
    "coverageByFeatures": [
        {
            "feature": "Wall",
            "coverage": 1.0
        }
    ]},
    {"name": "TestcaseB",
    "description": "Testing API",
    "coverageByFeatures": [
        {
            "feature": "Door",
            "coverage": 2.0
        }
    ]},
    {"name": "TestcaseC",
    "description": "Testing API",
    "coverageByFeatures": [
        {
            "feature": "Room",
            "coverage": 3.0
        }
    ]}]
}

###
DELETE http://localhost:5001/testcase/product/619f9a502957cb7f3d2dccc0

###
PATCH  http://localhost:5001/testcase/619f4d881102c1ca3a1385c6
Content-Type: application/json

{
    "name": "TestcaseB" 
}
