GET http://localhost:5001/testcase/product/619f4cea44686c0bb92a6d14

###
GET http://localhost:5001/testcase/feature/619f4d601102c1ca3a1385bc

###
POST http://localhost:5001/testcase/619f67a0104fac532794c14a
Content-Type: application/json

{
    "data": 
    [{"name": "TestcaseA",
    "description": "Testing API",
    "coverageByFeatures": [
        {
            "feature": "Window",
            "coverage": 1.5
        }
    ]},
    {"name": "TestcaseB",
    "description": "Testing API",
    "coverageByFeatures": [
        {
            "feature": "Door",
            "coverage": 1.0
        }
    ]},
    {"name": "TestcaseC",
    "description": "Testing API",
    "coverageByFeatures": [
        {
            "feature": "Window",
            "coverage": 1.5
        }
    ]}]
}

###
DELETE http://localhost:5001/testcase/product/619f4cea44686c0bb92a6d14

###
PATCH  http://localhost:5001/testcase/619f4d881102c1ca3a1385c6
Content-Type: application/json

{
    "name": "TestcaseB" 
}
